### ISSUE TITLE
Beginner Issue

### ISSUE THREAD

**Issue by mirmahathir1** [Badhan-BUET-Zone/badhan-backup#101]
Run the backup command

**Comment by hmasum52** [comment]
@mirmahathir1 vai I need this to complete the task ig
https://github.com/Badhan-BUET-Zone/badhan-backup/blob/6d7312bc1bb781d49ec00f6b7098ad16e1e65349/README.md?plain=1#L8

**Comment by mirmahathir1** [comment]
@hmasum52 
I have DMed you with the necessary files. Please continue now.

**Comment by hmasum52** [comment]
@mirmahathir1 vai I have been able to backup the database in firebase  


![image](https://github.com/Badhan-BUET-Zone/badhan-backup/assets/55390870/bb1cf67c-d0c3-4eb5-b4ed-68ef5bdfa153)
![image](https://github.com/Badhan-BUET-Zone/badhan-backup/assets/55390870/c0f84598-a911-41c4-85e9-7be463c43ec3)
